name: generate snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-light&color_snake=#1A73E8&color_dots=#EBEDF0,#D2E3FC,#8AB4F8,#4285F4,#1A73E8
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#8AB4F8&color_dots=#21262D,#174EA6,#1A73E8,#4285F4,#8AB4F8
      - uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
